### ISSUE TITLE
nmap flags

### ISSUE THREAD

**Issue by andregironda** [shodan-labs/iotdb#1]
Would prefer to see more, e.g.,:
nmap -n -Pn -sSU -pT:0-65535,U:0-65535 -v -A <ip>
and
nmap -6 -n -Pn -sSU -pT:0-65535,U:0-65535 -v -A <ip>

**Comment by achillean** [comment]
Good idea to prevent DNS resolution and include port 0 for TCP. Doing a UDP scan would be nice but can take a very long time to complete, so I'm not sure everybody is up for doing that but I've added it to the README. Thank you for the improvements!
